### ISSUE TITLE
negative unicode property via \P is not supported

### ISSUE THREAD

**Issue by riffraff** [tom-lord/regexp-examples#4]
`/\P{Word}/.examples` causes  an error, but it should in theory be possible to handle easily cause `\p{^Word}/.examples` works ok.

**Comment by tom-lord** [comment]
Great spot. I was actually aware of this just after releasing v1.0.0 (and hoped noone would notice haha!). The gem also needs to handle the edgier edge case:

    /\P{^name}/

(i.e. Double negatives)!

This will all be fixed in v1.1.0, as I'm making significant changes to how named properties are handled anyway - see the pending pull request.

**Comment by tom-lord** [comment]
Actually, I changed my mind and just pushed this fix to v1.0.1:

https://github.com/tom-lord/regexp-examples/commit/a1852510fc809aa6f4ac63542b3b6e30a9fd33b1

Fixed.
