### ISSUE TITLE
Can a reverse abilty be made?

### ISSUE THREAD

**Issue by bararchy** [tom-lord/regexp-examples#8]
Not an issue just something I thought about, can a reverse application be made, which takes a string and creates a Regex for it ? 

P.S
Your gem is really cool, thanks for the hard work !

**Comment by tom-lord** [comment]
The problem is, there's not really "an answer" to that problem you describe. 

For example, what regex matches the following strings: `"abcd"`, `"aadd"`, `"adbc"`? 

`/.{4}/`? `/a.{3}/`?  `/[a-d]{4}/`?  `/a.*d/`? ... 

Not only is it a very difficult problem to solve in general, but there is unfortunately no such thing as a "right" answer! 

One interesting tool you could look at that may  help you is the gem: `verbal_expressions`

**Comment by bararchy** [comment]
@tom-lord Thanks for the gem referance and the quick answer, while I was waiting for a response I looked around and found this: http://regex.inginf.units.it/

They apperently created a ML project that can infact generate a Regex for a couple of text examples, really cool thing :)

Any way, I'll play around with ```verbal_expressions``` and ```classifier
```

Thanks
