### ISSUE TITLE
symlink unimplemented when installing

### ISSUE THREAD

**Issue by MarioRuiz** [tom-lord/regexp-examples#9]
I get this message when installing it on windows 10:
C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:388:in `symlink': symlink() function is unimplemented on this machine (NotImplementedError)

**Comment by tom-lord** [comment]
Ahhh yes, Windows 10... :laughing: 

I have no idea why sym links aren't supported on your machine/Windows 10. However, there is currently only _one_ sym link in the gem, which you can see in [this](https://github.com/tom-lord/regexp-examples/tree/master/db) folder.

The purpose of those files is to support changes in unicode ranges mapped by named properties (e.g. `/\p{Greek}/.random_example`) _between different ruby versions_. But, since the definitions haven't actually changed between every version, I used a sym link to optimise the data stored.

I wrote that code a long time ago now, and in hindsight I think a better solution would actually be: Rather than using symbolic links at all, if there is no `pstore` file defined for your ruby version then automatically use the highest defined version below it. (E.g. if you were to run this gem with ruby `v2.5` today, then it would automatically reference the `unicode_ranges_2.4.pstore`).

I'll have a dig into the code soon and work out a (fairly simple, I think) fix for you. In the meantime, you could just clone the repo, remove that one file and install them gem manually.

**Comment by tom-lord** [comment]
Hi @MarioRuiz, could you please try installing the latest gem version now (v1.3.0)? I think your issue should hopefully be resolved.

**Comment by MarioRuiz** [comment]
Works like magic now.
I like the idea of this gem. I've been working on something similar internally. I'll try to be a good contributor. 
Thank you!

**Comment by tom-lord** [comment]
Awesome :) Thanks for raising the issue!
